GET http://localhost:8080/

###
POST http://localhost:8080/authenticate

{
    "email": "admin@example.com",
    "password": "secret"

}

###
GET http://localhost:8080/movies


###
GET http://localhost:8080/movies/1

###
GET http://localhost:8080/genres